### ISSUE TITLE
看起来不错

### ISSUE THREAD

**Issue by redapple0204** [Class04OpenSourceORG/ETransV2#1]
但是tcp链接真的安全可靠吗？

**Comment by lizongzeshunshun** [comment]
@redapple0204 tcp是最可靠的协议啊

**Comment by redapple0204** [comment]
@lizongzeshunshun UDP打洞....

**Comment by lizongzeshunshun** [comment]
@redapple0204 udp不可靠，不过有改版：kcp 兼顾高性能和高稳定性，准备重写一个（不过现在技术还没这么高

**Comment by redapple0204** [comment]
@lizongzeshunshun 我也觉得......暂时tcp好了
话说我觉得atom实在是太好用了。

**Comment by lizongzeshunshun** [comment]
@redapple0204
对 vs code也不错

**Comment by redapple0204** [comment]
@lizongzeshunshun 没错，你觉得哪个markdown比较好？
